export const SUPPORTED_LOCALES = ['ja', 'en'];
export const DEFAULT_LOCALE = 'ja';

const UI = {
  ja: { all:'すべて',code:'コード集',exception:'例外',compilerError:'コンパイルエラー',compilerWarning:'コンパイル警告',logic:'論理エラー',concept:'仕組み',heroEyebrow:'逆引きプログラミング言語リファレンス',heroTitle1:'やりたいことも、',heroTitle2:'壊れた理由も。',heroDescription:'コード例、例外、コンパイル診断、仕組みをひとつの検索で。',searchPlaceholder:'例: JSON / null / compiler error',categories:'種類',language:'言語',searchButton:'検索',recommended:'おすすめ',searchResults:q=>`「${q}」の検索結果`,resultCount:c=>`${c}件`,noResults:'一致する項目がありません。',back:'← 一覧に戻る',summary:'一言でいうと',cause:'原因',fix:'直し方',codeHeading:'コード',why:'なぜ？',tips:'補足',related:'関連',copy:'コピー',copied:'コピーしました',copyFailed:'コピー失敗',topics:'トピック',sort:'並び順',sortRecommended:'おすすめ順',sortTitle:'名前順',sortRecent:'最近見た順',sortFavorites:'お気に入り優先',favoritesOnly:'☆ お気に入り',recentOnly:'最近見た',activeFilters:'選択中',clearFilters:'すべて解除',favoriteAdd:'お気に入りに追加',favoriteRemove:'お気に入りから削除',untranslatedBadge:'未翻訳',fallbackBanner:'選択した言語の翻訳がまだありません。このページは日本語で表示しています。',contentLoadFailed:f=>`記事の取得に失敗しました: ${f}`,duplicateId:id=>`記事IDが重複しています: ${id}` },
  en: { all:'All',code:'Code recipes',exception:'Exceptions',compilerError:'Compiler errors',compilerWarning:'Compiler warnings',logic:'Logic pitfalls',concept:'Concepts',heroEyebrow:'Reverse lookup programming-language reference',heroTitle1:'What you want to do,',heroTitle2:'and why it broke.',heroDescription:'Search recipes, exceptions, compiler diagnostics, and concepts in one place.',searchPlaceholder:'e.g. JSON / null / compiler error',categories:'Categories',language:'Language',searchButton:'Search',recommended:'Recommended',searchResults:q=>`Search results for “${q}”`,resultCount:c=>`${c} results`,noResults:'No matching articles.',back:'← Back to list',summary:'In short',cause:'Cause',fix:'Fix',codeHeading:'Code',why:'Why?',tips:'Notes',related:'Related',copy:'Copy',copied:'Copied',copyFailed:'Copy failed',topics:'Topics',sort:'Sort',sortRecommended:'Recommended',sortTitle:'Title',sortRecent:'Recently viewed',sortFavorites:'Favorites first',favoritesOnly:'☆ Favorites',recentOnly:'Recent',activeFilters:'Active filters',clearFilters:'Clear all',favoriteAdd:'Add to favorites',favoriteRemove:'Remove from favorites',untranslatedBadge:'Not translated',fallbackBanner:'English translation is not available yet. This article is being shown in Japanese.',contentLoadFailed:f=>`Failed to load article content: ${f}`,duplicateId:id=>`Duplicate article ID: ${id}` }
};
function supported(locale){ return SUPPORTED_LOCALES.includes(String(locale ?? '')); }
export function resolveLocale({ search='', storedLocale='' }={}) { const q=new URLSearchParams(String(search)).get('lang'); if(supported(q)) return q; if(supported(storedLocale)) return String(storedLocale); return DEFAULT_LOCALE; }
export function withLangParam(url, locale) { const raw=String(url??''); const hashIndex=raw.indexOf('#'); const hash=hashIndex>=0?raw.slice(hashIndex):''; const before=hashIndex>=0?raw.slice(0,hashIndex):raw; const qi=before.indexOf('?'); const path=qi>=0?before.slice(0,qi):before; const p=new URLSearchParams(qi>=0?before.slice(qi+1):''); p.set('lang',supported(locale)?String(locale):DEFAULT_LOCALE); const q=p.toString(); return `${path}${q?`?${q}`:''}${hash}`; }
export function uiText(locale,key,...args){ const d=UI[supported(locale)?locale:DEFAULT_LOCALE]??UI[DEFAULT_LOCALE]; const v=d[key]??UI[DEFAULT_LOCALE][key]??key; return typeof v==='function'?v(...args):v; }
