import { articleHash, articleIdFromHash, copyCode, highlightCSharp } from './article-ui.js';
import { matchesArticle } from './article-search.js';import { loadLocalizedContent } from './content-loader.js';import { resolveLocale, uiText, withLangParam } from './i18n.js';
import { TOPIC_DEFINITIONS, buildDiscoverySearch, deriveArticleTopics, filterArticlesByTopics, filterArticlesByTypes, parseDiscoveryState, pushRecent, sortArticles, toggleId } from './list-discovery.js';
import { renderTranslationBadge, renderTranslationBanner, typeLabel } from './translation-ui.js';import { renderWikiText } from './wiki-links.js';
const LOCALE_KEY='language-atlas-locale',FAVORITES_KEY='language-atlas-favorites',RECENT_KEY='language-atlas-recent';
let locale='ja',query='',all=[],visible=[],types=new Set(),topics=new Set(),sort='recommended',favorites=new Set(),recent=[];
const $=id=>document.getElementById(id),cards=$('cards'),empty=$('empty'),count=$('resultCount'),search=$('searchInput'),detail=$('detailContent');
function escapeHtml(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');}
function read(key,fallback=[]){try{const v=JSON.parse(localStorage.getItem(key)??'null');return v??fallback;}catch{return fallback;}}function write(key,v){try{localStorage.setItem(key,JSON.stringify(v));}catch{}}
async function loadJson(path){const r=await fetch(path);if(!r.ok)throw new Error(uiText(locale,'contentLoadFailed',path));return r.json();}
function applyUi(){document.documentElement.lang=locale;$('languageSelect').value=locale;$('heroEyebrow').textContent=uiText(locale,'heroEyebrow');$('heroTitle1').textContent=uiText(locale,'heroTitle1');$('heroTitle2').textContent=uiText(locale,'heroTitle2');$('heroDescription').textContent=uiText(locale,'heroDescription');search.placeholder=uiText(locale,'searchPlaceholder');$('searchButton').textContent=uiText(locale,'searchButton');$('asideTitle').textContent=uiText(locale,'categories');$('backButton').textContent=uiText(locale,'back');$('topicFilterLabel').textContent=uiText(locale,'topics');$('sortLabel').textContent=uiText(locale,'sort');$('selectedFiltersLabel').textContent=uiText(locale,'activeFilters');$('clearFiltersButton').textContent=uiText(locale,'clearFilters');$('favoritesOnlyButton').textContent=uiText(locale,'favoritesOnly');$('recentOnlyButton').textContent=uiText(locale,'recentOnly');document.querySelectorAll('[data-nav-type],[data-type]').forEach(b=>{if(!b.dataset.chapter)b.textContent=typeLabel(b.dataset.navType??b.dataset.type,locale);});}
function renderTopics(){const l=locale==='en'?'en':'ja';$('topicFilters').innerHTML=TOPIC_DEFINITIONS.map(t=>`<button type="button" class="topic-filter${topics.has(t.id)?' active':''}" data-topic="${t.id}">${escapeHtml(t.labels[l])}</button>`).join('');$('topicFilters').querySelectorAll('[data-topic]').forEach(b=>b.addEventListener('click',()=>{topics=toggleId(topics,b.dataset.topic);renderTopics();filter();}));}
function syncUrl(){const s=buildDiscoverySearch({query,types,topics,sort},location.search);history.replaceState(null,'',`${location.pathname}${s}${location.hash}`);}
function filter(){const words=query.toLowerCase().split(/\s+/).filter(Boolean);let rows=filterArticlesByTypes(all,types).filter(a=>words.every(w=>matchesArticle(a,w)));rows=filterArticlesByTopics(rows,topics);visible=sortArticles(rows,sort,{recentIds:recent,favoriteIds:favorites});syncUrl();renderCards();}
function renderCards(){cards.innerHTML=visible.map(a=>`<article class="card"><div class="card-toolbar"><div class="card-meta"><span class="badge ${a.type}">${escapeHtml(typeLabel(a.type,locale))}</span>${renderTranslationBadge(a,locale)}</div><button class="favorite-button${favorites.has(a.id)?' active':''}" data-favorite="${a.id}">${favorites.has(a.id)?'★':'☆'}</button></div><button class="card-open" data-id="${a.id}"><h3>${escapeHtml(a.title)}</h3><p>${escapeHtml(a.short)}</p><div class="tags">${(a.tags??[]).slice(0,3).map(t=>`<span class="tag">${escapeHtml(t)}</span>`).join('')}</div></button></article>`).join('');cards.querySelectorAll('.card-open').forEach(b=>b.addEventListener('click',()=>location.hash=articleHash(b.dataset.id)));cards.querySelectorAll('[data-favorite]').forEach(b=>b.addEventListener('click',()=>{favorites=toggleId(favorites,b.dataset.favorite);write(FAVORITES_KEY,[...favorites]);filter();}));empty.style.display=visible.length?'none':'block';count.textContent=uiText(locale,'resultCount',visible.length);$('listTitle').textContent=query?uiText(locale,'searchResults',query):uiText(locale,'recommended');}
function find(id){return all.find(a=>a.id.toLowerCase()===String(id??'').toLowerCase())??null;}function text(v){return renderWikiText(v,find);}
function codeBlock(title,code,cls=''){return `<div class="block code-block"><div class="code-block-head"><h2>${escapeHtml(title)}</h2><button class="copy-code" data-copy-code="${encodeURIComponent(code)}">${uiText(locale,'copy')}</button></div><div class="code ${cls}">${String(code).split('\n').map((line,i)=>`<div class="code-line" data-line="${i+1}"><span class="code-text">${highlightCSharp(line)||' '}</span></div>`).join('')}</div></div>`;}
function open(id){const a=find(id);if(!a)return showHome();recent=pushRecent(recent,a.id);write(RECENT_KEY,recent);const blocks=[`<div class="block"><h2>${uiText(locale,'summary')}</h2><div class="note">${text(a.summary)}</div></div>`];if(a.bad)blocks.push(codeBlock(uiText(locale,'cause'),a.bad,'bad'));if(a.good)blocks.push(codeBlock(uiText(locale,'fix'),a.good,'good'));if(a.code)blocks.push(codeBlock(uiText(locale,'codeHeading'),a.code));if(a.why)blocks.push(`<div class="block"><h2>${uiText(locale,'why')}</h2><p>${text(a.why)}</p></div>`);if(a.tips)blocks.push(`<div class="block"><h2>${uiText(locale,'tips')}</h2><p>${text(a.tips)}</p></div>`);detail.innerHTML=`${renderTranslationBanner(a,locale)}<div class="detail-head"><span class="badge ${a.type}">${typeLabel(a.type,locale)}</span><h1>${escapeHtml(a.title)}</h1><p>${text(a.short)}</p></div>${blocks.join('')}`;detail.querySelectorAll('[data-copy-code]').forEach(b=>b.addEventListener('click',()=>copyCode(decodeURIComponent(b.dataset.copyCode))));detail.querySelectorAll('[data-wiki-id]').forEach(b=>b.addEventListener('click',()=>location.hash=articleHash(b.dataset.wikiId)));$('homeView').classList.add('hidden');$('detailView').classList.remove('hidden');document.title=`${a.title} - Language Atlas`;}
function showHome(){$('detailView').classList.add('hidden');$('homeView').classList.remove('hidden');document.title='Language Atlas';filter();}function route(){const id=articleIdFromHash(location.hash);id?open(id):showHome();}
async function init(){let stored='';try{stored=localStorage.getItem(LOCALE_KEY)??'';}catch{}locale=resolveLocale({search:location.search,storedLocale:stored});const state=parseDiscoveryState(location.search);query=state.query;types=state.types;topics=state.topics;sort=state.sort;favorites=new Set(read(FAVORITES_KEY));recent=read(RECENT_KEY);applyUi();search.value=query;$('sortSelect').value=sort;const result=await loadLocalizedContent({fetchJson:loadJson,locale});all=result.articles.map(a=>({...a,topics:deriveArticleTopics(a)}));renderTopics();filter();route();}
$('searchForm').addEventListener('submit',e=>{e.preventDefault();query=search.value.trim();filter();});document.querySelectorAll('[data-query]').forEach(b=>b.addEventListener('click',()=>{query=b.dataset.query;search.value=query;filter();}));document.querySelectorAll('[data-type]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.chapter)return;types=b.dataset.type==='all'?new Set():toggleId(types,b.dataset.type);filter();}));document.querySelectorAll('[data-nav-type]').forEach(b=>b.addEventListener('click',()=>{types=b.dataset.navType==='all'?new Set():new Set([b.dataset.navType]);showHome();}));$('sortSelect').addEventListener('change',e=>{sort=e.target.value;filter();});$('clearFiltersButton').addEventListener('click',()=>{types.clear();topics.clear();query='';search.value='';renderTopics();filter();});$('homeButton').addEventListener('click',()=>{location.hash='';showHome();});$('backButton').addEventListener('click',()=>{location.hash='';showHome();});$('languageSelect').addEventListener('change',e=>{try{localStorage.setItem(LOCALE_KEY,e.target.value);}catch{}location.assign(withLangParam(`${location.pathname}${location.search}${location.hash}`,e.target.value));});window.addEventListener('hashchange',route);init().catch(e=>cards.innerHTML=`<div class="empty" style="display:block">${escapeHtml(e.message)}</div>`);
