const SIZE={main:{width:220,height:86},support:{width:180,height:68}};const GAP=40;
function size(n){return SIZE[n.kind==='support'?'support':'main'];}function width(n){return n.width??size(n).width;}function height(n){return n.height??size(n).height;}
export function extractSupportSnippet(article,maxLines=4){const bad=typeof article?.bad==='string'?article.bad.trim():'';const code=typeof article?.code==='string'?article.code.trim():'';const source=bad||code;if(!source)return'';return source.split('\n').slice(0,maxLines).join('\n');}
export function buildQuestChapter(articles,chapter){const byId=new Map(articles.map(a=>[a.id,a]));const configs=new Map(chapter.nodes.map(n=>[n.id,n]));const nodes=chapter.nodes.map(c=>{const a=byId.get(c.id);if(!a)return null;const kind=c.kind??'main';return{...a,kind,code:c.code??(kind==='support'?extractSupportSnippet(a):''),prerequisites:[...(c.prerequisites??[])],attachedTo:c.attachedTo??null,lane:c.lane,offsetY:c.offsetY??0};}).filter(Boolean);const edges=[];for(const n of chapter.nodes){for(const p of n.prerequisites??[])if(configs.has(p))edges.push({source:p,target:n.id,kind:'prerequisite'});if((n.kind??'main')==='support'&&n.attachedTo&&configs.has(n.attachedTo))edges.push({source:n.attachedTo,target:n.id,kind:'support'});}return{id:chapter.id,title:chapter.title,description:chapter.description,nodes:computeQuestLayout(nodes),edges};}
export function computeQuestLayout(nodes){const byId=new Map(nodes.map(n=>[n.id,n]));const memo=new Map();const visiting=new Set();function depth(n){if(memo.has(n.id))return memo.get(n.id);if(visiting.has(n.id))return 0;visiting.add(n.id);const parents=(n.prerequisites??[]).map(id=>byId.get(id)).filter(Boolean);const d=parents.length?Math.max(...parents.map(depth))+1:0;visiting.delete(n.id);memo.set(n.id,d);return d;}const used=new Map();const staged=nodes.map(n=>{let d=depth(n);if(n.kind==='support'&&n.attachedTo&&byId.has(n.attachedTo))d=depth(byId.get(n.attachedTo))+1;const next=used.get(d)??0;const lane=Number.isFinite(n.lane)?n.lane:next;used.set(d,Math.max(next+1,lane+1));return{...n,depth:d,lane};});return reflowQuestLayout(staged);}
export function reflowQuestLayout(nodes,measurements=new Map()){const sized=nodes.map((n,i)=>{const f=size(n),m=measurements.get(n.id)??{};return{...n,width:m.width??n.width??f.width,height:m.height??n.height??f.height,order:i};});const depths=[...new Set(sized.map(n=>n.depth??0))].sort((a,b)=>a-b);const x=new Map();let nextX=120;for(const d of depths){x.set(d,nextX);nextX+=Math.max(...sized.filter(n=>(n.depth??0)===d).map(n=>n.width))+110;}const positions=new Map();for(const d of depths){let y=110;for(const n of sized.filter(n=>(n.depth??0)===d).sort((a,b)=>(a.lane??0)-(b.lane??0)||a.order-b.order)){positions.set(n.id,{x:x.get(d),y:y+(n.offsetY??0)});y=(positions.get(n.id).y)+n.height+GAP;}}return sized.map(({order,...n})=>({...n,...positions.get(n.id)}));}
export function assignEdgeRouteOffsets(edges){return edges.map((_,i)=>(i%3-1)*8);}
export function routeQuestEdgePoints(source,target,nodes,offset=0){const start={x:source.x+width(source),y:source.y+height(source)/2};const end={x:target.x,y:target.y+height(target)/2};const mid=(start.x+end.x)/2+offset;return[start,{x:mid,y:start.y},{x:mid,y:end.y},end];}
export function questWorldBounds(nodes){if(!nodes.length)return{width:900,height:560};return{width:Math.max(900,Math.max(...nodes.map(n=>n.x+width(n)))+140),height:Math.max(560,Math.max(...nodes.map(n=>n.y+height(n)))+120)};}
